import org.gradle.api.provider.ValueSource
import org.gradle.api.provider.ValueSourceParameters
import java.time.LocalDate
import java.time.format.DateTimeFormatter

plugins {
    alias(libs.plugins.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.config)
    alias(libs.plugins.dokka)
}

description = "Ktor plugin and Kotlin DSL for building voice AI applications with Vapi.ai"

tasks.withType<Zip> {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// ValueSources are read fresh on each build (configuration-cache-safe), so APP_RELEASE_DATE and
// BUILD_TIME reflect the actual build time rather than a frozen configuration-cache value.
abstract class CurrentDateValueSource : ValueSource<String, ValueSourceParameters.None> {
    override fun obtain(): String =
        LocalDate.now().format(DateTimeFormatter.ofPattern("MM/dd/yyyy"))
}

abstract class CurrentTimeValueSource : ValueSource<Long, ValueSourceParameters.None> {
    override fun obtain(): Long = System.currentTimeMillis()
}

val releaseDate = providers.of(CurrentDateValueSource::class) {}
val buildTime = providers.of(CurrentTimeValueSource::class) {}

buildConfig {
    useKotlinOutput()
    packageName(project.group.toString())
    documentation.set("Generated by BuildConfig plugin")
    buildConfigField("String", "APP_NAME", "\"${project.name}\"")
    buildConfigField("String", "VERSION", provider { "\"${project.version}\"" })
    buildConfigField("String", "RELEASE_DATE", releaseDate.map { "\"$it\"" })
    buildConfigField("long", "BUILD_TIME", buildTime.map { "${it}L" })
}

dependencies {
    api(project(":vapi4k-utils"))

    api(libs.ktor.client.core)
    api(libs.ktor.client.cio)
    api(libs.ktor.client.websockets)
    api(libs.ktor.client.encoding)
    api(libs.ktor.client.content.negotiation)
    api(libs.ktor.server.core)
    api(libs.ktor.server.cio)
    api(libs.ktor.server.websockets)
    api(libs.ktor.server.compression)
    api(libs.ktor.server.auth)
    api(libs.ktor.server.content.negotiation)
    api(libs.ktor.server.call.logging)
    api(libs.ktor.server.html.builder)
    api(libs.ktor.server.metrics.micrometer)
    api(libs.ktor.serialization)
    api(libs.micrometer.registry.prometheus)
    api(libs.exposed.kotlin.datetime)

    testImplementation(kotlin("test"))
    testImplementation(libs.kotest.runner)
    testImplementation(libs.kotest.assertions)
    testImplementation(libs.ktor.server.tests)
}

dokka {
    pluginsConfiguration.html {
        homepageLink.set("https://github.com/vapi4k/vapi4k")
        footerMessage.set("vapi4k-core")
    }
    dokkaSourceSets.configureEach {
        sourceLink {
            includes.from("../docs/packages.md")
            localDirectory.set(file("src/main/kotlin"))
            remoteUrl.set(uri("https://github.com/vapi4k/vapi4k/blob/master/vapi4k-core/src/main/kotlin"))
            remoteLineSuffix.set("#L")
        }
    }
}
